src/lib.rs
The code compiles today without the trailing semicolon because of [this bug](https://github.com/rust-lang/rust/issues/34543), which we fixed in https://github.com/rust-lang/rust/pull/34660. The fix is currently in beta.
As far as we are aware, this is the only crate for which we could not implement warnings to preserve backwards comparability (see https://github.com/rust-lang/rust/pull/34660#issuecomment-230699973 for details).
=> Add a trailing semicolon to avoid breakage.

Cargo.toml, examples/simple_crud.rs, src/lib.rs, src/signing.rs
First off, thank you for writing this library. The API is exactly at the level it should be for 99% of the interactions that people have with S3, as opposed to the extremely detailed APIs of something like rusoto or aws_sdk_rust.
What I found when working with the library, though, is that many potential sources of errors were handled with `panic!`. This was unworkable for my needs since I would be running this from a server. I started by rewriting chunks of the code to use the Rust `Result` type, and started to notice more and more places where I could "rustify" code. In the end I reworked quite a bit, and ended up with something that I think will be easier to use, maintain, and extend.
I'm opening this PR mainly as an option for you - if you like the changes I've made, great! I'd love to …
=> Rewrite for testability, error handling,  separation of concerns

Cargo.toml, build.rs, examples/simple_crud.rs, src/lib.rs, src/serde_types.in.rs
This PR adds XML deserialization to the list function.  The docs for the struct fields are copied from S3.
=> Add serde_xml deserialization for S3 list

src/serde_types.rs
Hey!
I was trying to list the contents of a few buckets, but encountered a couple of problems:
- File sizes larger than `i32::MAX` cause Serde XML to complain about receiving a string instead of `i32` (in my case, I had a 6GB file that caused this), so I changed the type of `Owner.size` to `u64`.
- For some buckets, the fields `Owner`, `NextMarker`, `Delimiter`, `Marker`, `EncodingType`, and `CommonPrefixes` were missing in the API response (again, causing Serde XML to fail), so I made them optional.
These are of course breaking changes since they change public types, but for me they work ;-)
=> Large file sizes and missing fields when listing bucket contents

src/bucket.rs, src/error.rs, src/serde_types.rs
The bucket list API is currently dysfunctional. AWS sends responses that fail to parse, as Serde expects the fields to exist in responses. Additionally, when the request fails, the developer doesn't get very good information why.
This PR fixes the bucket list API by making non-default fields optional. In addition, it makes the errors returned by AWS into first class errors in the library.
The other methods need to be updated with AWS errors too – this is just the first push, but at least it makes the bucket listing API work.
=> Fixed the bucket list API

src/deserializer.rs, src/lib.rs, src/serde_types.rs, src/signing.rs
The main issue was possibly because of a change in the implementation of serde-rs or serde-xml-rs and the details are here: https://github.com/RReverser/serde-xml-rs/issues/44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/17)
=> Solved an issue with parsing ListBucketResult returned from S3.

src/region.rs
Digital Ocean is rolling out Spaces.  Spaces is compatible with Amazon S3.  This patch makes this library work with Digital Ocean Spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/23)
=> Add digital ocean's nyc3 region to the list of possible regions

src/bucket.rs, src/lib.rs, src/request.rs
Last time I implemented an error handling for one function. Now that I'm using many other functions too, I realised, upon encountering an error, that I completely forgot about the others!
You can always see from the HTTP status returned by AWS that some error has happened, if its 400 or over. So it makes sense to implement a general error handling. Also, the AwsError type contains the fields that, according to the API, are always populated. This is enough to get a gist of of the error.
At the moment the methods in this crate happily return with the "no error" path, even if error has happened. This is very surprising from the user perspective, since the methods return a S3Result. This PR fixes this by checking the errors at the request.rs file, upon finishing a request.
---
This change …
=> Moved error handling to the Request object, so every method now checks for errors.

src/serde_types.rs
This change lines up the name of the field for common prefixes from rust-rs with the one used by S3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/25)
=> Fixed a typo when deserializing common prefixes from a bucket listing

Cargo.toml, src/command.rs, src/error.rs, src/lib.rs, src/request.rs, src/signing.rs
When this library was originally created there wasn't a good pure-Rust solution for synchronous HTTP requests. That library (reqwest) now exists, so convert existing Curl-based code to use it.
This primarily reduces the number of external system/C-language dependencies for the library, but the reqwest library also has much nicer ergonomics than curl.
@durch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/34)
=> Convert to using reqwest library

src/bucket.rs, src/credentials.rs, src/request.rs
Changes made to the `Credentials` type cause it fall back to loading credentials from the config file usually kept at `~/.aws/credentials`. This is certainly useful in normal operation, but when running unit tests we don't want to be accidently using people's real keys.
Note that the keys I've used as stand-ins are all example credentials from the AWS documentation, not real keys.
@durch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/33)
=> Do not use real user credentials in unit tests

src/bucket.rs
By calling `to_owned()` on the bucket, the `Future` can be returned without a borrow and thus plays better with e.g. `actix-web`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/49)
=> Remove lifetime in Bucket::list_all_async

Cargo.toml, src/bin/simple_crud.rs, src/bucket.rs, src/command.rs, src/credentials.rs, src/error.rs, src/lib.rs, src/region.rs, src/request.rs, src/signing.rs
Closes #47. 
Adds async version of the `list` bucket method (`list_all_async`), renames `list` to `list_all`. Also adds `list_page` and `list_page_async` `Bucket` methods. Simplifies returned futures so that only a top level future remains, making usage much more ergonomic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/48)
=> Finalize 0.18.0-beta

src/credentials.rs
Currently, `rust-s3` reads `/sys/hypervisor/uuid` to determine whether the instance is EC2 or not. But some EC2 instances don't have `/sys/hypervisor/uuid`, but have `/sys/class/dmi/id/board_vendor`. This change will enable `rust-s3` to run also in the latter type EC2 instances.
Reference:
https://github.com/scylladb/scylla/commit/2a4ba883c8e9c3351ff69064bb4d09954ff001c4#diff-23bb822fd3271daf086e185150f31517
Closes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/68)
=> Fix to avoid unintentional fails

src/bucket.rs
The old url was fixed to the generic amazon s3 endpoint. This is
naturally not applicable for anyone using different regions (or s3
providers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/69)
=> Correct bucket endpoint url

s3/bin/simple_crud.rs
S3Error was still being imported from the root but it was moved to the error module, so I updated the import
=> update import of S3Error from root to new mod

s3/Cargo.toml, s3/src/request.rs
The reqwest documentation tells us that we should reuse client istance as it holds connection pool internally
https://docs.rs/reqwest/0.10.4/reqwest/struct.Client.html
=> caching reqwest client instance as advised by reqwest documentation

s3/src/bucket.rs
Hi, 
> NextContinuationToken is sent when isTruncated is true, which means there are more keys in the bucket that can be listed. 
According to [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#AmazonS3-ListObjectsV2-response-NextContinuationToken), it should ensure `isTruncated` to be `true` before using `NextContinuationToken`, or it will cause forever loop (in my case).
@durch Please review.
=> Fix continue logic of list_buckets

s3/Cargo.toml, s3/src/signing.rs
the Url crate does not encode (for example) parentheses, but AWS
wants them for the purposes of signing. This change decodes
the Url and then re-encodes it with AWS's idea of canonical
percent-encoding.
=> handle S3 URLs that are encoded differently in percent-encoding and AWS

s3/src/request.rs
Hi @durch .
I'm using rust-s3 for my project, and I found that the following codes will panic my program with unreachable exception.
```
let url = bucket.presign_put("/test.file", 86400).unwrap();
```
After review the codes I found something not correct, but I'm not sure whether there should be `Command::PresignPut` arm in `fn presigned_canonical_request`, so plz review.
Besides, the `Host` header in `presigned_authorization` should be generated according to the `cfg!(feature = "path-style")` .
=> Fixing `PresignPut`

aws-creds/Cargo.toml, s3/Cargo.toml, s3/src/request.rs
This removes the need for openssl in `reqwest` and `attohttpc` dependencies, currently it is not possible to compile without openssl.
Add the following to Cargo.toml in your project:
```toml
rust-s3 = {version = "0.24", default-features = false, features = ["rustls-tls"]}
aws-creds = {version = "0.24", default-features = false, features = ["rustls-tls"]}
[patch.crates-io]
aws-creds = { git = "https://github.com/koplas/rust-s3/", branch="rustls"}
rust-s3 = { git = "https://github.com/koplas/rust-s3/", branch="rustls"}
```
Check for openssl with:
`cargo tree | grep openssl`
=> Make openssl optional

s3/src/bucket.rs
Before this, local paths obtained through directory traversal, `tempfile::NamedFile::path` or anything like that would first have to be converted to strings, which does UTF8 validation and is just generally pointless boilerplate.
This is a breaking change since it can break type inference (for example if people were calling `.put_object_stream(my_local_path.as_ref(), my_s3_path)`).
=> Allow types other than string slices for local paths

README.md, s3/Cargo.toml, s3/src/bucket.rs, s3/src/bucket_ops.rs, s3/src/command.rs, s3/src/lib.rs, s3/src/request.rs
Closes #127 
Adds `BucketCreate` and `BucketDelete` commands, as well as bucket ops scaffolding, available on crates.io as `0.26.2-beta0`
=> BucketCreate and BucketDelete Commands

s3/src/bucket.rs, s3/src/command.rs, s3/src/request.rs, s3/src/serde_types.rs, s3/src/utils.rs
Added the HeadObject command.
I have updated the tests to include this command.
I only have access to AWS so I was only able to actually run the aws tests:
* `test_put_head_get_delete_object` 
* `test_put_head_get_delete_object_blocking`
I'm assuming that they will pass for GC and wasabi.
Please let me know if I can make any improvements or if there is a better way to make the changes etc.
=> Add HeadObject command

s3/src/bucket.rs
The range is inclusive: `[start, end]` instead of `[start, end)`. I ran into an issue because of this, so I thought I'd make the documentation clearer.
=> Improve `get_object_range` documentation

s3/src/bucket.rs
Addition to #99, so creating buckets with custom s3-conformance servers work.
Extra info:
Prior to the current beta, it's possible to create a bucket with path style by building bucket and using command directly, but it's not feasible in the latest upstream. IIRC, it's due to request not being public.
=> add: impl create_with_path_style

s3/Cargo.toml, s3/src/bucket.rs, s3/src/utils.rs
Hello, this tiny PR removes the dependency on async-std when he feature flag `with-tokio` is enabled (in the current state, this means that we are pulling the async-std runtime and dependency tree even when we only make use of the tokio runtime).
Happy holidays, and many thanks for this crate, by the way :)
=> Delete a dependency on async-std when tokio is selected

s3/src/bucket.rs
There was no way to access these from the object in the crate, so I
added them back.
Fixes #185
=> Add Tag impl with key and value methods

s3/src/blocking.rs, s3/src/request.rs
All 3 provided client implementations contain an `is_success` method for status codes, and the behavior of all 3 of those methods is the same, so this standardizes the behavior between the clients.
=> Make all fail-on-err variations run the same check

aws-creds/Cargo.toml, aws-creds/src/credentials.rs
If an application is simply constructing a Credentials struct from existing values for `rust-s3`, it doesn't need an http client bundled into the library. This change makes the http client in aws-creds optional behind a feature flag, but still enabled by default.
=> Make attohttpc optional for credentials

s3/src/bucket.rs, s3/src/request.rs, s3/src/request_trait.rs, s3/src/surf_request.rs, s3/src/utils.rs
Rather than passing std::io::Write to async methods, define separate tokio/async-std/std versions of the `response_data_to_writer` method on `Request` to accept the proper sync/async Write trait for the environment
=> Use async write for tokio,async-std

s3/src/bucket.rs, s3/src/command.rs, s3/src/request_trait.rs, s3/src/serde_types.rs
Google Cloud Storage doesn't support the newer ListObjectsV2 call.
This is a rebase of https://github.com/durch/rust-s3/pull/175. (That PR was closed with no explanation, I'm not sure what happened there..)
=> Add support for the older ListObjects API

s3/src/bucket.rs
There already was a special case in put_object_stream() for a small files,
where the multi-part upload was aborted if the input turned out to be
small enough to fit in one chunk. But we can do better than that, and not
initiate the multi-part upload in the first place, avoiding two round
trips to S3 (one to initiate, and another to abort the multi-part upload).
While we're at it, refactor the loop slightly.
=> If file is smaller than one chunk, don't initiate multi-part upload

README.md, s3/Cargo.toml, s3/src/bucket.rs
This one function pulls in both minidom and quick-xml, and we have never used it. Would be nice to be able to get rid of those extra dependencies.
=> Make minidom dependency optional

README.md, s3/Cargo.toml, s3/src/bucket.rs, s3/src/utils.rs
This can heavily reduce dependency count for applications that don't otherwise depend on some of the `futures-*` crates.
=> Import futures-io crate directly instead of through futures

aws-creds/src/credentials.rs
This is technically a breaking change, but no (infinite) timeout is a bad default, and incentivises libraries to override the global timeout at all sorts of different values. We have been running with a 30-second timeout in production for more than a month, without any problem: in a healthy state, credentials requests return in milliseconds. That seems like a reasonable, if conservative, default.
=> aws-creds: default to a 30-second request timeout

s3/src/bucket.rs
No (infinite) timeout is a bad default. It's easy for libraries to override their bucket objects' timeout, but we should probably default to *some* timeout, rather than letting requests remain stuck forever (up to TCP timeout).
I'm not 100% convinced this change is a good idea: large uploads or downloads can last a more than 30 seconds... On the other hand, it's easier to observe a timeout and relax the maximum duration, compared to realising that a program is stuck because there's no timeout on S3 calls. What do you think?
=> s3/bucket: default to 30-second request timeout

README.md, s3/Cargo.toml, s3/src/bucket.rs, s3/src/request_trait.rs, s3/src/surf_request.rs, s3/src/utils.rs
Was partially broken due to #230 introducing new imports from `futures`, and partially due to me missing that it should have been `futures_util` in one place instead in #227.
=> Import futures-* crates directly instead of through futures

README.md, s3/Cargo.toml
`tokio-stream` has a dependency on `tokio` and is only used within the `request` module, which depends on the `with-tokio` feature.  As such, in order to completely prevent `tokio` from appearing in the crate graph, this crate must be marked optional and enabled when `with-tokio` is requested, omitted otherwise.
Also includes two drive-by typo-fixes in the features section of the readme.
=> cargo: Move `tokio-stream` create behind the `with-tokio` feature

s3/Cargo.toml, s3/src/request_trait.rs, s3/src/signing.rs
and make the right behavior the default.
This was merged in #236, but never made it to a release and now it's gone again on `develop` too. I'm hoping that was just an accident.
=> Remove never-encode-slash feature

aws-creds/Cargo.toml
Bumping rust-ini gets rid of a duplicate ordered-multimap for us.
=> aws-creds: Bump rust-ini to 0.18

s3/bin/simple_crud.rs, s3/src/bucket.rs, s3/src/command.rs, s3/src/request_trait.rs, s3/src/signing.rs
Added a field `custom_queries` to command `PresignGet`.
The motivation is to be able to set the `response-content-disposition` query parameter (causing the server to respond with the `Content-Disposition` header set to the specified value) to enable the browser to save the presigned url as a file using the specified file name.
=> Add custom_queries to command PresignGet

s3/src/serde_types.rs
**Describe the bug**
Some S3 self-hosted servers do not returns all fields during listing files. This merge request makes that fields optional.
I run with this problem with S3 servers:
- https://github.com/datenlord/s3-server (also written in Rust)
- https://github.com/chrislusf/seaweedfs
I tested only `ListObjectsV2` and `GetObjectRange` commands with above servers.
**Additional context**
I checked whats fields are required in `aws-sdk-rus` and there almost all are optional, even `key`. 
- `ListObjectsV2Output` - https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/s3/src/output.rs#L2366=
- `Object` - https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/s3/src/model.rs#L13517=
=> make some fields in struct ListBucketResult optional

s3/Cargo.toml
The `time::format_description::well_known::Rfc2822` used in this crate
has been added since `time` version `0.3.6`. Therefore, Cargo.toml must set `0.3.6`.
=> Set the patch version of `time`

s3/src/bucket.rs
If multipart chunk upload failed - abort the upload
Fixes https://github.com/durch/rust-s3/issues/273
=> fix: abort multipart upload if chunk PutObject request failed

s3/src/bucket.rs, s3/src/command.rs, s3/src/request_trait.rs
This is based on the patch from @chuigda, rebased onto master with
docs extended.
Fixes #172
=> Allow setting the content type for multipart uploads

aws-creds/src/credentials.rs
Fixes #286
**WARNING**: This is a possibly breaking change due to the use of a newtype wrapper in a public interface.
The newtype wrapper is completely transparent and derefs to its inner type, however, this could still break and require adding an `.into()`.
=> Fix date and time parsing

s3/Cargo.toml, s3/src/bucket.rs, s3/src/request.rs, s3/src/request_trait.rs, s3/src/surf_request.rs
This is a partial implementation of #275, allowing the streaming of download requests using async `Stream<Item = Result<Bytes, S3Error>>` streams.
There is no equivalent version for synchronous rust.
=> Request streaming

s3/src/bucket.rs, s3/src/utils.rs
Partial fix for issues mentioned in https://github.com/durch/rust-s3/issues/305.
This should make uploading objects using streams properly async again.
=> Make put object stream proper async again

aws-creds/src/credentials.rs
The new credentials refresh feature is extremely useful to our project - thank you! However, we're finding our logs have lots of noise with a refresh every 30 minutes. While we could change our RUST_LOG env var, I suspect it's more useful for the typical user for this log to be at the debug level.
=> Change credential refresh log from info to debug

aws-creds/Cargo.toml, aws-creds/src/credentials.rs, aws-creds/src/error.rs, s3/Cargo.toml, s3/src/bucket.rs, s3/src/error.rs, s3/src/serde_types.rs, s3/src/signing.rs
The xml-rs crate used by serde-xml-rs seems to be
unmaintained [1, 2] and has received an active RUSTSEC advisory [3] due to unfixed parsing issues [4].
Luckily, XML usage in the crates here is minimal
and can be one-to-one migrated to the recommended
quick-xml [5]. The download stats on crates.io show that quick-xml is currently being favoured.
[1] https://github.com/netvl/xml-rs/issues/219
[2] https://github.com/RReverser/serde-xml-rs/issues/180
[3] https://rustsec.org/advisories/RUSTSEC-2022-0048
[4] https://github.com/rustsec/advisory-db/issues/1121
[5] https://crates.io/crates/quick-xml
=> Migrate from serde-xml-rs to quick-xml

s3/src/bucket.rs, s3/src/signing.rs
According to https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html, the header should be ordered to obtain a correct signature.
=> fix: presigned custom header order

examples/gcs-tokio.rs
I believe this comment is here by mistake, carried over from other examples.
=> remove misleading comment from GCP example

aws-region/src/region.rs
Added the [new Israel region](https://aws.amazon.com/blogs/aws/now-open-aws-israel-tel-aviv-region/) variant.
=> Add il-central-1 region

aws-creds/src/credentials.rs
Fixes error where crate does not compile with feature `http-credentials` disabled
=> Add feature-gate on Credentials::refresh

README.md, s3/Cargo.toml, s3/src/bucket.rs, s3/src/command.rs, s3/src/error.rs, s3/src/lib.rs, s3/src/post_policy.rs, s3/src/request/async_std_backend.rs, s3/src/request/blocking.rs, s3/src/request/request_trait.rs, s3/src/request/tokio_backend.rs, s3/src/utils/mod.rs, s3/src/utils/time_utils.rs
- the presigned post needs to provide as a response the post URL and all the fields that need to be added
- redo the presign_post function to accept only a PostPolicy which is a builder of the post policy
- add a time mock to allow for better testing
@durch please provide commends on code-style choices and contracts.
Right now this is a fully working model to get presigned posts actually working based on the documentation from these pages
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html
I even got the same exact signature when faking the dates and base64 payload as the post-example  😄  I had to fake the payload as …
=> Rework presign_post to be correct

s3/Cargo.toml
`aws-creds` is re-exposed from `s3`. This means, technically, we don't need to depend on `aws-creds` when we already depend on `s3`. However, if we need the `http-credentials` from `aws-creds`, then we do need to depend on both which can create problems:
- `aws-creds` gets updated, but `s3` didn't yet get updated with the new version of `aws-creds`
- our code uses `Credential` from the new version of `aws-creds` and try to use it with `s3` which depends on the old version of `aws-creds`
- you get an error
That's usually the reason for re-exposing `aws-creds` from `s3` (to avoid this different versions of the same crate in the dependency tree). But today, there is no way to have `http-credentials` without importing both. This PR should solve that.
=> feat: re-expose 'http-credentials' from 's3'

s3/Cargo.toml
0.34.0-rc4 doesn't compile with a version lower than this due to the absence of `impl From<Bytes> for Vec<u8>`.
The way to ensure this does not happen anymore is to have a CI run with [cargo-minimal-versions](https://crates.io/crates/cargo-minimal-versions).
=> Fix Bytes version requirement

README.md
According to [github search](https://github.com/search?q=repo%3Adurch%2Frust-s3%20fail-on-err&type=code), fail-on-error does not actually add any panic! code-paths, just ones which return errors.
=> Fix fail-on-err description

s3/Cargo.toml, s3/src/bucket.rs, s3/src/error.rs, s3/src/request/tokio_backend.rs
This commit fixes rustls feature being dependant on native-tls and binding to libcrypto.
fixes: #369
=> fix: rustls causing openssl to be built

s3/src/bucket.rs, s3/src/request/async_std_backend.rs, s3/src/request/blocking.rs, s3/src/request/request_trait.rs, s3/src/request/tokio_backend.rs, s3/src/utils/mod.rs
By relaxing size constraint.
Avoid double indirection. Instead of having to pass `&mut &mut dyn AsyncWrite`, we can pass `&mut dyn AsyncWrite`, for example. The use case for dynamic dispatch is object-safe traits. Static dispatch is unaffected.
`tokio` and `std` do the same thing, for example [tokio::io::copy](https://docs.rs/tokio/latest/tokio/io/fn.copy.html) and [std::io::copy](https://doc.rust-lang.org/stable/std/io/fn.copy.html).
[Example of the problem and desired outcome.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b329ee2e751f2af663dc2fd72c362fdb)
=> Make Read and Write generics friendlier to dynamic dispatch

s3/src/bucket_ops.rs
According to: https://docs.aws.amazon.com/AmazonS3/latest/API/API_Owner.html#API_Owner_Contents, only certain regions support `DisplayName` for the bucket. This causes problem for my bucket (eu-north-1) once I use `bucket.exists()`, it throws the following Error:
`S3(SerdeXml(Custom("missing field DisplayName")))`
Thus, it should be `Option<String>` to support all regions.
=> Make BucketOwner `DisplayName` optional

s3/src/bucket.rs, s3/src/command.rs, s3/src/request/request_trait.rs
When generating pre-signed URLs for uploading multipart parts, the query must include the parameters `partNumber` and `uploadId`. Unfortunately, this is not possible with the current interface of this Crate, which assumes that signed URLs don't need to pass custom queries.
This PR adjusts the interface to accept custom queries, too.
=> Support custom queries when generating presigned put URLs

s3/Cargo.toml, s3/src/bucket.rs, s3/src/command.rs, s3/src/request/async_std_backend.rs, s3/src/request/request_trait.rs, s3/src/request/tokio_backend.rs, s3/src/serde_types.rs
=> Feat: bucket lifecycle configuration impl 

s3/src/request/request_trait.rs
I needed these functions to avoid unnecessary copy so hopefully adding them is ok.
=> Add bytes_mut and into_bytes for ResponseData

s3/src/request/request_trait.rs
Garage S3 returns `400 Bad Request` when `content-length` is signed but not required (e.g., `ListBuckets`).
- Skip `content-length` and `content-type` headers for:
- `ListBuckets`
Verified against Garage S3-compatible storage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/428)
=> fix(s3): exclude content-length for ListBuckets

s3/src/bucket.rs, s3/src/command.rs, s3/src/request/request_trait.rs
Add two new methods to support uploading objects with custom HTTP headers on a per-request basis:
- **put_object_with_content_type_and_headers**: upload with explicit content-type and custom headers.
- **put_object_with_headers**: uploads an object with optional custom headers; uses `"application/octet-stream"` as the default `Content-Type`.
Custom headers are attached to the PUT request via the headers method in the request trait. Following the same design approach as the existing `put_object` and `put_object_with_content_type` methods.
**Use Case:**
Enable per-upload customization of HTTP headers such as Cache-Control, allowing control over caching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add put_object_with_headers method to bucket

s3/src/bucket.rs
Fixes `Bucket::get_object_range_to_writer()` when using sync impl features. The function was incorrectly marked `async`, which this change removes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/413)
=> Fix Bucket::get_object_range_to_writer() sync impl

aws-creds/Cargo.toml, aws-creds/src/credentials.rs
It is now possible to load Credentials from locations other than `$HOME/.aws/credentials`.
aws-cli allows you to customize where it looks for the `credentials` file using the `AWS_SHARED_CREDENTIALS_FILE` environment variable ([docs](https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html#file-location-change)). We're using that at my $JOB. The way I implemented it here doesn't look at that environment variable, just takes an arbitrary path. That is enough for my specific use-case, but it might be reasonable to also look at the aforementioned variable in `from_profile`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/406)
=> Add a way to load Credentials from a profile file at custom location.
