durch/rust-s3

src/lib.rs
Removed a bunch of unwraps and changed over to using try! instead.  The library will have to be revved a major version because this will break clients.
=> Return result instead of unwrap()

src/lib.rs
The format of RFC2822 is somewhat malleable, so including it in signed headers can (and does) cause signature mismatches. We do include the X-Amz-Date header, so requests are still properly limited to a date range and can't be used again e.g. by reply attacks.
Change logic for building headers to add the Date header _after_ the Authorization header has been generated. This prevents Date from being part of the signed headers.
Fixes #8
=> Fix bug causing 403 on signed requests

src/region.rs
Just adding the remaining Digital Ocean hosts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/28)
=> Add Digital Ocean Amsterdam and Singapore regions.

src/region.rs
Adds 3 new regions:
- ap-northeast-3
- cn-north-1
- cn-northwest-1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/32)
=> Add new regions (ap-northeast-3, china)

Cargo.toml, src/bin/simple_crud.rs, src/bucket.rs, src/command.rs, src/region.rs, src/request.rs, src/serde_types.rs, src/signing.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/36)
=> Scaffolding for bucket ops, bucket location()

Cargo.toml, src/bucket.rs, src/request.rs
Closes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/41)
=> Add streaming downloads with the stream_object Bucket method

Cargo.toml, README.md, src/bucket.rs, src/lib.rs, src/request.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/44)
=> Async get_object and get_object_stream Bucket methods, #43

Cargo.toml, src/bin/simple_crud.rs, src/bucket.rs, src/credentials.rs, src/lib.rs, src/request.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/56)
Closes #55
Closes #52
=> Instance credentials and sync spawns

Cargo.toml, src/credentials.rs
Closes #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/59)
=> Token from file

Cargo.toml, src/credentials.rs, src/error.rs
Closes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/64)
=> Fail more gracefully if not on an EC2 instance

Cargo.toml, src/bin/simple_crud.rs, src/request.rs
Closes #63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/65)
=> Add integrity check on put, fix implicit text coercion

Cargo.toml, src/request.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/70)
=> Upgrade reqwest and tokio to stable versions (for 0.19.0)

src/credentials.rs
Support for container credentials to allow use in Fargate containers https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/73)
=> Added support for container credentials

src/credentials.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/durch/rust-s3/75)
=> Fargate support

s3/src/request.rs
I used this library and suddenly I saw an incomprehensible link from this file
=> Remove debug println!

.github/workflows/rust.yml, README.md, aws-creds/Cargo.toml, aws-creds/src/credentials.rs, s3/Cargo.toml, s3/bin/simple_crud.rs, s3/src/bucket.rs, s3/src/request.rs
Closes #96.
Heads up @iammichiel this PR addresses the issue of runtime `path-style` configuration
=> Bucket path style

s3/Cargo.toml, s3/src/bucket.rs, s3/src/command.rs, s3/src/request.rs, s3/src/signing.rs
Closes #116, #115, #120
@koplas thank you raising both tickets, this PR addresses them both. It would be great if you could test `0.25.0-beta5` version, and report back any other/new issues.
`0.25.0-beta5` has been pushed to crates.io
=> Allow custom header presign, encode presign paths

aws-creds/Cargo.toml, aws-creds/src/lib.rs, s3/Cargo.toml
* Bump base64 version
* Bump rust-ini version
=> Upgrade dependencies (#124)

s3/src/bucket.rs, s3/src/lib.rs, s3/src/utils.rs
=> Calculate etag for local files

s3/src/bucket.rs, s3/src/command.rs, s3/src/request.rs
Tentative implementation for #134. Hopefully, I got the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35) right. Let me know what you think.
=> Implement get object range

.github/workflows/rust.yml, .ignore, s3/Cargo.toml, s3/Makefile, s3/src/blocking.rs, s3/src/bucket.rs, s3/src/command.rs, s3/src/lib.rs, s3/src/request.rs, s3/src/request_trait.rs, s3/src/signing.rs, s3/src/utils.rs
Splits off sync and async code behind feature flags
=> Split off sync

aws-creds/src/credentials.rs
Additionally, make the method public and remove the need for cloning some strings.
=> Fix `Credentials::from_instance_metadata`

aws-creds/Cargo.toml, aws-creds/src/credentials.rs, aws-creds/src/lib.rs, aws-region/Cargo.toml, aws-region/src/lib.rs, aws-region/src/region.rs, s3/Cargo.toml, s3/src/blocking.rs, s3/src/bucket.rs, s3/src/bucket_ops.rs, s3/src/lib.rs, s3/src/request.rs, s3/src/request_trait.rs, s3/src/signing.rs, s3/src/surf_request.rs, s3/src/utils.rs
switched to anyhow error and replaced some match statements with function chaining.
using the anyhow error should fix https://github.com/durch/rust-s3/issues/145
=> switch to anyhow error

s3/Cargo.toml, s3/src/request.rs
=> upgrade tokio to 1.0

s3/src/bucket.rs, s3/src/command.rs, s3/src/request_trait.rs, s3/src/serde_types.rs
Hello, this adds basic support for listing multiparts uploads, and aborting them.
=> Add methods to list and abort multipart uploads

s3/Cargo.toml, s3/src/bucket.rs, s3/src/lib.rs, s3/src/serde_types.rs
=> Fix XML tags parsing

s3/Cargo.toml, s3/src/bucket.rs, s3/src/lib.rs, s3/src/smol_request.rs, s3/src/utils.rs
When I use `smol::block_on()` to call functions asynchronously, there will be tokio runtime errors, so I support smol asynchronous calls with new feature (`with-smol`).  you can check [https://github.com/smol-rs/smol](url) about smol.
Thanks your project, lol...
=> feat: support smol

aws-creds/src/credentials.rs
The value is global, so it's not always possible to restore a previous
setting value, but it's better than nothing.
This change won't be as useful once #220 is in: that patch should reduce
the pressure for libraries to override the credentials fetch timeout.
=> aws-creds: return the previous timeout when overriding

aws-region/src/region.rs, s3/src/bucket_ops.rs, s3/src/request.rs, s3/src/serde_types.rs, s3/src/signing.rs
Fixes the build error from #246 by moving request parsing outside of `anyhow!()` and formatting
=> Fix build error - #246

s3/src/bucket.rs, s3/src/request_trait.rs, s3/src/signing.rs
=> Lumeohq presign fix

s3/src/signing.rs
FIX #283
Also remove a bunch of unnecessary intermediate string allocations
=> Fix presigining

s3/src/bucket.rs
MinIO doesn't set a namespace in the response. They also don't call it `Values`, but `Value`. 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Tagging>
<TagSet>
<Tag>
<Key>foo</Key>
<Value>bar</Value>
</Tag>
</TagSet>
</Tagging>
```
=> fix: `get_object_tagging` for minio

aws-creds/Cargo.toml, s3/Cargo.toml
These features should allow using the vendored libssl.
=> added native-tls-vendored feature

s3/src/utils.rs
The etag algorithm was incorrect for files where the chunk size was < 2. The algorithm re-hashed the hashes, which isn't what is supposed to happen.
This PR fixes the algorithm by not rehashing the digest for chunk size 1.
=> Fix etag generation for small files

aws-region/src/region.rs
Add support for the new AWS region based in Zurich
=> add support for new region eu-central-2

README.md, s3/Cargo.toml, s3/src/bucket.rs, s3/src/error.rs, s3/src/request/blocking.rs, s3/src/request/tokio_backend.rs, s3/src/utils.rs
Closes https://github.com/durch/rust-s3/issues/278.
=> refactor(s3): don't depend on reqwest

s3/src/request/request_trait.rs
=> Remove superfluous println

s3/src/request/request_trait.rs, s3/src/request/tokio_backend.rs
=> Only send metadata on Initiate of multipart upload

s3/src/bucket.rs
=> Fix put_object_stream sync for small files

aws-creds/src/credentials.rs, aws-creds/src/error.rs
=> Add imds v2 support

s3/src/bucket.rs, s3/src/command.rs, s3/src/request/async_std_backend.rs, s3/src/request/request_trait.rs, s3/src/request/tokio_backend.rs, s3/src/serde_types.rs
=> Feat: bucket lifecycle configuration impl
